kafka:
  address: "localhost:9092"
  topic: "test"
  partition: 0
productAPI:
  address: "http://localhost:7002/api/v1/"
searchAPI:
  address: "http://localhost:7001/api/v1/"
databaseDsn: "user=postgres dbname=indexer-api password=qwerty host=db port=5432 sslmode=disable"