kafka:
  address: "localhost:9092"
  topic: "test"
  partition: 0
productAPI:
  address: "http://localhost:7002"
  path: "/api/v1/product/full-info"
searchAPI:
  address: "http://localhost:7001"
  path: "/api/v1/product/update"