server:
  address: ":7001"
databaseDsn: "user=postgres dbname=product-api password=qwerty host=localhost port=5432 sslmode=disable"
s3:
  bucket: "product-api-bucket"
  url: "http://localhost:9444"
  region: "us-west-2"
  accessKeyID: "AKIAIOSFODNN7EXAMPLE"
  secretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"