server:
  host: ""
  port: 7002
databaseDsn: "user=postgres dbname=product-api password=qwerty host=postgres port=5432 sslmode=disable"
s3:
  bucket: "product-api-bucket"
  url: "http://ninja:9000"
  region: "us-west-2"
  accessKeyID: "AKIAIOSFODNN7EXAMPLE"
  secretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
kafka:
  address: "kafka:9092"
  topic: "test"
  partition: 0